baseURL = 'https://timothyelems.github.io/'
# baseURL = 'localhost'
languageCode = 'en-us'
title = 'timothy elems'
author = "timothyelems"
# theme = "papermod"
# theme = "saral"
theme = "hello-friend-ng"
# pagination.pagerSize = 10


# [permalinks]
  # melhor = "/melhor/"

[pagination]
  disableAliases = false
  pagerSize = 17
  path = 'page'
 
favicon = "static/favicon.ico"

canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[params]
  [params.author]
    name = "timothy elems"
  
  logoText = "timothy elems"
  isBlogFocused = true
  showHeroImage = true
  showResumeButton = true
  showReadingTime = true
  subtitle = 'problem solver'
  math = true
  canonifyURLs = true
  enableRobotsTXT = true
  enableGitInfo   = false
  enableEmoji     = true
  enableMissingTranslationPlaceholders = false
  disableRSS     = false
  disableSitemap = false
  disable404     = false
  disableHugoGeneratorInject = false
  ShowShareButtons = true
  justifyContent = false
  ShareButtons = ["linkedin", "twitter", "github"]

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "thoughts and opinions"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  # enableGlobalLanguageMenu = true

  enableThemeToggle = false

  # Metadata mostly used in document's head
  description = "Timothy Elems' Musings"
  keywords = "musings"
  images = [""]

  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = ">"
    logoText     = "timothy elems"
    logoHomeLink = "/"

  # [[params.social]]
  #   name = "twitter"
  #   url  = "https://twitter.com/timothyelems"

  [[params.social]]
    name = "email"
    url  = "mailto:elemstimothy@protonmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/TimothyElems"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/tim-elems"

  # [[params.social]]
  #   name = "stackoverflow"
  #   url  = "https://www.stackoverflow.com/"

  [params.footer]
    trademark = 2024
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "powered by <a href=\"http://gohugo.io\">hugo</a>"
    ]

[services]
  [services.rss]
      # Maximum number of items in the RSS feed.
      limit = 42

# [languages]
#   [languages.en]
#     weight    = 1
#     copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
#   [languages.en.params]
#     subtitle  = "Hello Friend NG Theme"

#   [languages.fr]
#     weight    = 2
#     copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
#   [languages.fr.params]
#     subtitle  = "Hello Friend NG Theme"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['@@', '@@']]
          inline = [['@', '@']]
    
[menu]
  [[menu.main]]
    name = "melhor"
    # pre = "pen-tool"
    url = "/melhor/"
    weight = 10
  # [[menu.main]]
  #   name = "Khalil Mack"
  #   pre = "pen-tool"
  #   url = "/khalil/"
  #   weight = 20
  # [[menu.main]]
  #   name = "Projects"
  #   pre = "projects"
  #   url = "/projects/"
  #   weight = 30
  # [[menu.main]]
  #   name = "About"
  #   pre = "about"
  #   url = "/about/"
  #   weight = 40
  [[menu.main]]
    name = "tocar"
    # pre = "contact"
    url = "/contact/"
    weight = 30
  [[menu.main]]
   name = "viagem"
  #  pre = "journey"
   url = "https://timothyelems.github.io/resume/"
   weight = 40


  [module]
  [module.hugoVersion]
    extended = true
    min = "0.123.0"
    # max = "0.123.0"

[[params.social]]
    url = "https://x.com/timothyelems"
    icon = "/social/x.svg"
    name = "X"

[[params.social]]
    url = "mailto:me"
    icon = "/social/email.png"
    name = "Email"

[[params.social]]
    url = "https://github.com/TimothyElems"
    icon = "/social/github.svg"
    name = "Github"
